CREATE TABLE [dbo].[Share]
(
	[Id] INT IDENTITY NOT NULL,
    [AssetId] INT NOT NULL, 
    [Message] NVARCHAR(250) NOT NULL, 
	[ToUserId] NVARCHAR(128) NOT NULL,
	[FromUserId] NVARCHAR(128) NOT NULL,
	[CreateDt] SMALLDATETIME NOT NULL,
    [ReadDt] SMALLDATETIME NULL, 
    CONSTRAINT [PK_Share] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_Share_Asset_Id] FOREIGN KEY (AssetId) REFERENCES Asset(Id),
    CONSTRAINT [FK_Share_ToUserId_Id] FOREIGN KEY (ToUserId) REFERENCES AspNetUsers(Id),
    CONSTRAINT [FK_Share_FromUserId_Id] FOREIGN KEY (FromUserId) REFERENCES AspNetUsers(Id)
)
