//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.Services.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public Share()
        {
            this.Views = new HashSet<View>();
        }
    
        public int Id { get; set; }
        public int AssetId { get; set; }
        public string ToUserId { get; set; }
        public string FromUserId { get; set; }
        public System.DateTime CreateDt { get; set; }
        public Nullable<System.DateTime> ReadDt { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ICollection<View> Views { get; set; }
        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
    }
}
